// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "topic_modeling",
  "name": "Topic Modeling",
  "description": "This plugin groups messages in channel into upto 10 specified topics",
  "version": "0.1.0",
  "min_server_version": "5.29.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "Configure your demo plugin settings below.",
    "footer": "Footer: The code for this demo plugin can be found [here](https://github.com/mattermost/mattermost-plugin-demo).",
    "settings": [
      {
        "key": "defaultgreeting",
        "display_name": "The default answer:",
        "type": "text",
        "help_text": "The default greeting if no name is available",
        "placeholder": "Hi there",
        "default": "Hi there"
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
